import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire(path.join(process.env.TEMP, 'h06-browser', 'package.json'));
const { chromium } = require('playwright-core');
const ids = JSON.parse(fs.readFileSync('../simulator/config/operational-fleet.json','utf8')).assets.map(a=>a.transformer_id);
const output = path.resolve('screenshots/operational-ten'); fs.mkdirSync(output,{recursive:true});
const browser = await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const evidence={at:new Date().toISOString(),ids,responses:[],errors:[]};
try {
 const page=await browser.newPage({viewport:{width:1600,height:1050}});
 page.on('pageerror',e=>evidence.errors.push(e.message));
 page.on('response',async r=>{if(r.url().includes('/api/v1/'))try{evidence.responses.push({url:r.url(),status:r.status(),at:new Date().toISOString(),body:await r.json()});}catch{}});
 await page.goto(process.env.CONSOLE_UI_URL || 'http://127.0.0.1:5173',{waitUntil:'domcontentloaded'});
 await page.getByRole('button',{name:`Monitor ${ids[0]}`,exact:true}).waitFor({timeout:30000});
 const cards=async()=>await page.locator('.asset-grid .transformer-card').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('aria-label').replace('Monitor ','')));
 assert.deepEqual(await cards(),ids.slice(0,5));
 assert(await page.getByText(/Page 1 of 2/).isVisible());
 assert(await page.getByRole('button',{name:'Previous',exact:true}).isDisabled());
 await page.waitForFunction(()=>document.querySelector('.asset-grid')?.textContent.includes('SIMULATED source'),{timeout:30000});
 evidence.page1=await page.locator('.asset-grid').innerText();
 await page.screenshot({path:path.join(output,'page1.png'),fullPage:true});
 await page.getByRole('button',{name:'Next',exact:true}).click();
 assert.deepEqual(await cards(),ids.slice(5));
 assert(await page.getByText(/Page 2 of 2/).isVisible());
 assert(await page.getByRole('button',{name:'Next',exact:true}).isDisabled());
 await page.waitForFunction(()=>document.querySelector('.asset-grid')?.textContent.includes('SIMULATED source'),{timeout:30000});
 evidence.page2=await page.locator('.asset-grid').innerText();
 await page.screenshot({path:path.join(output,'page2.png'),fullPage:true});
 const selected=async id=>{
  await page.waitForFunction(id=>document.querySelector('[aria-label="Selected transformer measurements"] h2')?.textContent===id,id);
  await page.waitForFunction(()=>document.querySelector('[aria-label="Selected transformer measurements"]')?.textContent.includes('SYNTHETIC'),{timeout:30000});
  const latest=evidence.responses.filter(r=>r.url.endsWith('/'+id+'/latest')&&r.status===200).at(-1)?.body;
  assert(latest && latest.telemetry.transformer_id===id && latest.analytics.transformer_id===id);
  const dom=await page.getByRole('region',{name:'Selected transformer measurements'}).innerText();
  const number=new Intl.NumberFormat(undefined,{maximumFractionDigits:3}).format(latest.telemetry.current_l1);
  assert(dom.includes(number+' '+latest.telemetry.acquisition.field_units.current_l1));
  return {id,latest,dom};
 };
 await page.getByRole('button',{name:`Monitor ${ids[9]}`,exact:true}).click();
 evidence.tx10=await selected(ids[9]);
 await page.getByRole('combobox',{name:'Asset',exact:true}).selectOption(ids[0]);
 evidence.tx01=await selected(ids[0]);
 assert.notEqual(evidence.tx10.latest.telemetry.acquisition.snapshot_id,evidence.tx01.latest.telemetry.acquisition.snapshot_id);
 const before=evidence.tx01.latest.telemetry.timestamp;
 await page.waitForFunction(old=>document.querySelector('[aria-label="Source and freshness"]')?.textContent.includes('Snapshot:')&&!document.querySelector('[aria-label="Source and freshness"]').textContent.includes(old),evidence.tx01.latest.telemetry.acquisition.snapshot_id,{timeout:30000});
 evidence.updated=await selected(ids[0]);assert(evidence.updated.latest.telemetry.timestamp>before);
 await page.screenshot({path:path.join(output,'detail.png'),fullPage:true});
 assert.deepEqual(evidence.errors,[]);
 fs.writeFileSync(path.join(output,'browser.json'),JSON.stringify(evidence,null,2));
 console.log('PASS real browser: exactly ten active IDs, two ordered five-card pages, boundary controls, TX10/TX01 isolation, live timestamp advancement and matching API readings');
} finally {await browser.close();}
