import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire(path.join(process.env.TEMP, 'h06-browser', 'package.json'));
const { chromium } = require('playwright-core');
const evidence = path.resolve('screenshots'); fs.mkdirSync(evidence, {recursive:true});
const browser = await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
const responses=[], errors=[];
try {
 const page=await browser.newPage({viewport:{width:1600,height:1050}});
 page.on('pageerror',e=>errors.push(e.message));
 page.on('response',async r=>{if(r.url().includes('/api/v1/'))try{responses.push({url:r.url(),status:r.status(),at:new Date().toISOString(),body:await r.json()});}catch{}});
 await page.goto(process.env.CONSOLE_UI_URL || 'http://127.0.0.1:5174',{waitUntil:'domcontentloaded'});
 await page.getByRole('heading',{name:'Transformer overview',exact:true}).waitFor();
 await page.getByRole('button',{name:'Monitor H06-SIM-05',exact:true}).waitFor({timeout:40000});
 await page.waitForFunction(()=>document.querySelector('.asset-grid')?.textContent?.includes('SIMULATED source'),{timeout:30000});
 const registryResponses=responses.filter(r=>/transformers\?/.test(r.url));
 const registered=registryResponses.flatMap(r=>r.body.items || []).map(a=>a.id);
 assert(registered.includes('H07-b41b39-25'),'Registry pagination omitted portfolio assets');
 await page.getByRole('textbox',{name:'Search assets'}).fill('H07-b41b39');
 await page.getByRole('button',{name:'Monitor H07-b41b39-01',exact:true}).waitFor();
 await page.waitForFunction(()=>document.querySelector('.asset-grid')?.textContent?.includes('SIMULATED source'),{timeout:30000});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:path.join(evidence,'overview.png'),fullPage:true});
 await page.getByRole('textbox',{name:'Search assets'}).fill('');
 await page.getByRole('button',{name:'Monitor H06-SIM-05',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[aria-label="Selected transformer measurements"]')?.textContent?.includes('SYNTHETIC'),{timeout:30000});
 const checkAsset=async id=>{
  await page.waitForFunction(id=>document.querySelector('[aria-label="Selected transformer measurements"]')?.querySelector('h2')?.textContent===id,id);
  await page.waitForFunction(()=>document.querySelector('[aria-label="Source and freshness"]')?.textContent?.includes('SIMULATED'),{timeout:30000});
  const latest=responses.filter(r=>r.url.includes('/'+id+'/latest')&&r.status===200).at(-1)?.body;
  assert(latest && latest.transformer.id===id && latest.telemetry.transformer_id===id);
  const dom=await page.getByRole('region',{name:'Selected transformer measurements'}).innerText();
  assert(dom.includes(String(latest.telemetry.current_l1)+' '+latest.telemetry.acquisition.field_units.current_l1));
  return {id,latest,dom,source:await page.getByRole('region',{name:'Source and freshness'}).innerText()};
 };
 const first=await checkAsset('H06-SIM-05');
 await page.getByRole('heading',{name:'Oil-leak detection',exact:true}).waitFor();
 assert(await page.getByText(/No pressure measurement/).isVisible());
 await page.getByRole('img',{name:'Oil temperature event-time trend'}).waitFor({timeout:40000});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:path.join(evidence,'transformer-detail.png'),fullPage:true});
 await page.getByRole('combobox',{name:'Asset',exact:true}).selectOption('H07-b41b39-02');
 const second=await checkAsset('H07-b41b39-02');assert.notEqual(first.latest.telemetry.acquisition.snapshot_id,second.latest.telemetry.acquisition.snapshot_id);
 await page.getByRole('combobox',{name:'Asset',exact:true}).selectOption('H06-SIM-05');
 await checkAsset('H06-SIM-05');
 const snapshotBefore=responses.filter(r=>r.url.endsWith('/H06-SIM-05/latest')&&r.status===200).at(-1)?.body.telemetry.acquisition.snapshot_id;
 await page.waitForFunction(()=>document.querySelector('.source-strip')?.textContent?.includes('Snapshot:'),{timeout:15000});
 // Failure is a browser-level network interruption; backend and broker stay running.
 const lastSuccessBefore=await page.locator('.source-strip > div').nth(3).innerText();
 await page.route('**/api/v1/**',route=>route.abort());
 await page.getByText(/Latest telemetry: API disconnected/).waitFor({timeout:20000});
 const outage=await page.getByRole('region',{name:'Source and freshness'}).innerText();
 assert(outage.includes('API error'));assert.equal(await page.locator('.source-strip > div').nth(3).innerText(),lastSuccessBefore);
 await page.screenshot({path:path.join(evidence,'api-outage.png'),fullPage:true});
 await page.unroute('**/api/v1/**');
 await page.getByRole('alert').filter({hasText:'Latest telemetry:'}).getByRole('button',{name:'Retry'}).click();
 await page.waitForFunction(()=>!Array.from(document.querySelectorAll('[role="alert"]')).some(e=>e.textContent.includes('Latest telemetry:')),{timeout:30000});
 // Observe an actual new source identity in the selected DOM, rather than assuming a poll means new telemetry.
 await page.waitForFunction(snapshot=>{const text=document.querySelector('[aria-label="Source and freshness"]')?.textContent || '';return text.includes('Snapshot:')&&!text.includes(snapshot);},snapshotBefore,{timeout:40000});
 const snapshotAfter=responses.filter(r=>r.url.endsWith('/H06-SIM-05/latest')&&r.status===200).at(-1)?.body.telemetry.acquisition.snapshot_id;
 await page.getByRole('button',{name:'Predictive maintenance',exact:true}).click();
 await page.getByRole('region',{name:'RUL',exact:true}).waitFor();
 await page.waitForFunction(()=>document.querySelector('[aria-label="Energy"]')?.textContent?.includes('Calculation:'),{timeout:40000});
 await page.waitForFunction(()=>document.querySelector('[aria-label="RUL"]')?.textContent?.includes('Method:'),{timeout:30000});
 const resourceDOM=await page.getByRole('region',{name:'RUL',exact:true}).innerText();
 assert(responses.some(r=>r.url.endsWith('/H06-SIM-05/rul')&&r.status===200));
 assert(responses.some(r=>r.url.includes('/H06-SIM-05/energy?')&&r.status===200));
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Toggle navigation'}).click();
 await page.getByRole('button',{name:'Transformer monitoring',exact:true}).click();
 await page.getByRole('img',{name:'Oil temperature event-time trend'}).waitFor({timeout:30000});
 await page.waitForFunction(()=>!Array.from(document.querySelectorAll('[role="alert"]')).some(e=>e.textContent.includes('API disconnected')),{timeout:30000});
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:path.join(evidence,'mobile-detail.png'),fullPage:true});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile layout overflows');
 assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(evidence,'live-verification.json'),JSON.stringify({at:new Date().toISOString(),browser:await browser.version(),registryCount:new Set(registered).size,first,second,outage,lastSuccessBefore,snapshotBefore,snapshotAfter,actualSnapshotAdvanced:snapshotBefore!==snapshotAfter,resourceDOM,errors,responses},null,2));
 console.log('PASS actual API registry, two-asset DOM equality/isolation, six features, unavailable pressure, network failure/last-success preservation/recovery, RUL/energy, desktop/mobile screenshots');
} finally {await browser.close();}
